export enum Role {
    BENCH_MANAGER = 'BENCH_MANAGER',
    HIRING_MANAGER = 'HIRING_MANAGER',
    REQUIREMENT_MANAGER = 'REQUIREMENT_MANAGER',
    ADMIN = 'ADMIN',
    SUPER_ADMIN = 'SUPER_ADMIN',
    DEFAULT = 'DEFAULT',
}